apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: ${ECR_REGISTRY}/clo835-assignment1-webapp-image:v0.2
        ports:
        - containerPort: 8080
        env:
        - name: APP_COLOR
          value: "pink"
        - name: DBHOST
          value: "mysql-service.mysql.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "admin"
        - name: DATABASE
          value: "employees"