apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  namespace: assignment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: ${ECR_REGISTRY}:v0.1
        ports:
        - containerPort: 8080
        env:
        - name: APP_COLOR
          value: "blue"
        - name: DBHOST
          value: "mysql-service.mysql.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "admin"
        - name: DATABASE
          value: "employees"