apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
spec:
  selector:
    app: employees
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort